Beautify performance metrics docstrings
Unity-Technologies/datasetinsights pull request #100
Opened 2020-09-18 22:42 UTC by BlairLee

# Peer Review Information

Some of the metrics docstrings aren’t properly parsed. Update those improper docstrings.

# Pull Request Check List

- [x] Updated **documentation** for changed code.

2020-09-22 18:18 UTC, adason requested changes

2020-09-22 18:18 UTC, adason commented on datasetinsights/evaluation_metrics/average_precision_2d.py
> +r"""This module provides some common average precision metrics implementations
The rendered docstring looks like:
<img width="762" alt="Screen Shot 2020-09-22 at 10 47 18 AM" src="https://user-images.githubusercontent.com/786669/93918339-0a4e1b00-fcc1-11ea-9351-3669463a49ac.png">

I suggest improve the following things:

1. Hide urls and create hyperlinks. This reduces visual noise that does not break the flow of reading
2. This should be very clear what 2D this module offers. 

```
""" Average Precision metrics for 2D object detection

This module provides average precision metics to evaluate 2D object detection models, such as metrics defined in `coco evaluation <url>`_.  The most commonly used metrics are `MeanAveragePrecisionIOU50 <link>` and `MeanAveragePrecision <link>` which provide average precision for all labels considered.

These metrics are implemented based on `A <uri>` and `B <url>`.

metric `AveragePrecision` provide metrics for a given IOU and label. `AveragePrecisionIOU50` is 
  
"""
```

2020-09-22 18:18 UTC, adason commented on datasetinsights/evaluation_metrics/average_precision_2d.py
> +    .. math:: mAP^{IoU=50}=1/N\sum_{label=1}^{N}AP^{IoU=50}
The math should be improved to reflect typical formula convention.
```
.. math:: mAP(\\text{IOU=50})=\\frac{1}{N_{\\text{label}}}\sum_{\\text{label}}AP(\\text{label}, \\text{IOU=50})

where AP is the `AveragePrecision <link>` metrics competed separately for each label.
```

2020-09-22 18:18 UTC, adason commented on datasetinsights/evaluation_metrics/average_precision_2d.py
> +    .. math:: mAP^{IoUs} = 1/10\sum_{IoU=0.5}^{0.95}mAP^{IoU}
```
mAP = \\frac{1}{N_\\text{IOU}N_\\text{label}}\sum_{\\text{label}, \\text{IOU}}AP(\\text{label}, \\text{IOU})
```

2020-09-22 18:18 UTC, adason commented on datasetinsights/evaluation_metrics/average_recall_2d.py
> +r"""This module provides some common average recall metrics implementations
Same as `average_precision_2d.py`. Can you improve this?

2020-10-20 22:50 UTC, adason commented
@BlairLee What's the latest status of this PR? Can we close it?

2020-10-21 17:20 UTC, BlairLee commented
> @BlairLee What's the latest status of this PR? Can we close it?

I update the evaluation metrics docstrings. Now it's clear to users. I think we can merge it.

2020-11-04 20:53 UTC, adason approved these changes

2020-11-04 21:22 UTC, merged