Fixed index page
Unity-Technologies/datasetinsights pull request #158
Opened 2021-03-08 20:10 UTC by 86sanj

# Peer Review Information

- Fixed index page: Removed train/eval details

# Pull Request Check List

- [ ] Added **tests** for changed code.
- [ ] Updated **documentation** for changed code.

2021-03-08 21:59 UTC, BlairLee submitted a review, later dismissed

2021-03-08 21:59 UTC, BlairLee commented on docs/source/index.rst
>  We provide a sample `notebook <https://github.com/Unity-Technologies/datasetinsights/blob/master/notebooks/SynthDet_Statistics.ipynb>`_ to help you get started with dataset statistics for the `SynthD
The notebook link is invalid. Need to be updated.

2021-03-09 19:26 UTC, BlairLee commented on docs/source/index.rst
> +Dataset Insights maintains a pip package for easy installation. It can work in any standard Python environment using :code:`pip install datasetinsights` command. We support Python 3 (3.7 and 3.8).
Change back to >=3.7.

2021-03-09 19:29 UTC, adason requested changes

2021-03-09 19:29 UTC, adason commented on README.md
> +from datasetinsights.io.downloader import (UnitySimulationDownloader,
I will separate these three downloader into three code blocks and explain briefly what each block is trying to achieve.

2021-03-09 19:29 UTC, adason commented on README.md
> +from datasetinsights.datasets.unity_perception import (AnnotationDefinitions,
Let's separate metrics, captures and definitions here into separate code blocks. We can leave out egos and sensors for now as these are less used feature in the current perception package. Also, we should provide explanation in each code block to let user know what to expect.

2021-03-09 19:29 UTC, adason commented on README.md
> +You can explore the downloaded dataset [schema](https://datasetinsights.readthedocs.io/en/latest/Synthetic_Dataset_Schema.html#synthetic-dataset-schema) by using following API:
Users don't need to download datasets in order to use this package. This package should also work for development use cases when they generated the dataset on their workstation.

2021-03-09 19:29 UTC, adason commented on docs/source/index.rst
> +.. code-block:: python3
Fix this. See comments in README

2021-03-09 19:29 UTC, adason commented on docs/source/index.rst
> +.. code-block:: python3
Fix this. See comments in README

2021-03-10 20:04 UTC, adason requested changes

2021-03-10 20:04 UTC, adason commented on README.md
>  downloader.download(source_uri=source_uri, output=data_root)
I will suggest adding concrete variable 

```python3
from datasetinsights.io.downloader import UnitySimulationDownloader

source_uri = "usim://<some example here>"
dest = "~/data"
access_token = "XXX" 

downloader = UnitySimulationDownloader(access_token=access_token)
downloader.download(source_uri=source_uri, output=dest)
```

2021-03-10 20:04 UTC, adason commented on README.md
>  downloader.download(source_uri=source_uri, output=data_root)
Use concrete example

2021-03-10 20:04 UTC, adason commented on README.md
>  downloader.download(source_uri=source_uri, output=data_root)
use concrete example.

2021-03-10 20:04 UTC, adason commented on README.md
> +metric_def = MetricDefinitions(data_root="/data", version="my_schema_version")
The path here should be a follow after the dataset was downloaded. I suggest using a consistent path as in the download example.

2021-03-10 20:04 UTC, adason commented on README.md
> +Dataset Insights maintains a pip package for easy installation. It can work in any standard Python environment using `pip install datasetinsights` command. We support Python 3 (>= 3.7).
Why is this changed? Are we supporting python 3.9 now?

2021-03-11 00:29 UTC, BlairLee approved these changes

2021-03-11 19:08 UTC, adason approved these changes

2021-03-11 19:43 UTC, merged