Misc Dataset to COCO Transformer
Unity-Technologies/datasetinsights pull request #183
Opened 2021-10-25 18:28 UTC by Saurav-D

# Peer Review Information

Added MPII and LSPET dataset to COCO transformer.

# Pull Request Check List

- [ ] Added **tests** for changed code.
- [ ] Updated **documentation** for changed code.

2021-11-10 01:52 UTC, adason requested changes

2021-11-10 01:52 UTC, adason commented on datasetinsights/datasets/transformers/lspet2coco.py
> +joints_lspet = [
Python constant should be ALL CAPS. I would also recommend making this a tuple so that it's immutable.

2021-11-10 01:52 UTC, adason commented on datasetinsights/datasets/transformers/coco.py
> +coco_keypoints = [
Use ALL CAPS and tuple for python constants.

2021-11-10 01:52 UTC, adason commented on datasetinsights/datasets/transformers/lspet2coco.py
> +        annotation_file_path = self._data_root / "joints.mat"
Let's make this a separate variable so that we don'e assume folder structure for images and labels.

2021-11-10 01:52 UTC, adason commented on datasetinsights/datasets/transformers/lspet2coco.py
> +    def execute(self, output):
Why is this method empty?

2021-11-10 01:52 UTC, adason commented on datasetinsights/datasets/transformers/lspet2coco.py
> +class LSPETtoCOCOTransformer:
Need tests for this transformer.

2021-11-10 01:52 UTC, adason commented on datasetinsights/datasets/transformers/mpii2coco.py
> +class MPIItoCOCOTransformer:
Need tests for this transformer.

2022-02-28 19:35 UTC, Saurav-D commented
Moved to dataformatter.

2022-02-28 19:35 UTC, closed without merging