added graph filters
Unity-Technologies/datasetinsights pull request #21
Opened 2020-08-03 21:44 UTC by kalyanijagdale

# Peer Review Information

Added filters using label names for object count and visible pixels.
# Pull Request Check List

- [ ] Added **tests** for changed code.
- [x] Updated **documentation** for changed code.

2020-08-07 04:50 UTC, Saurav-D commented
Resolve merge conflict. Merge from master.

2020-08-11 18:07 UTC, BlairLee commented
You need to assign reviewers for this PR.

2020-08-12 02:44 UTC, Saurav-D commented on datasetinsights/visualization/app.py
> +_app = _init_app()
can this be initialized inside `get_app` method?

2020-08-12 02:45 UTC, Saurav-D commented on datasetinsights/visualization/app.py
> +def get_app():
Do we need this? Can we directly call _init_app?

2020-08-14 19:18 UTC, adason requested changes

2020-08-14 19:18 UTC, adason commented on datasetinsights/dashboard.py
> +def clean_data(value):
should be renamed to `get_data_root`?

2020-08-14 19:18 UTC, adason commented on datasetinsights/stats/visualization/object_detection.py
> +            # title="Light orientations",
Why is title commented out here? Should it be removed?

2020-08-14 19:18 UTC, adason commented on datasetinsights/stats/visualization/object_detection.py
> +            # title="Object orientations",
Why is title commented out here? Should it be removed?

2020-08-14 19:18 UTC, adason commented on datasetinsights/dashboard.py
> +        return overview.html_overview(data_root)
It's still confusing how the local variable `data_root` is available here. Can you make sure to read this value by calling `get_data_root` method? Can you add comments in code to explain this a little bit?

2020-08-14 21:50 UTC, adason approved these changes

2020-08-14 21:55 UTC, merged