Update to download command help text.
Unity-Technologies/datasetinsights pull request #52
Opened 2020-08-21 10:59 UTC by AdamPalmarUnity

# Peer Review Information

Adding help text to download command with examples

# Pull Request Check List

- [ ] Added **tests** for changed code.
- [ ] Updated **documentation** for changed code.

2020-08-21 19:32 UTC, adason requested changes

2020-08-21 19:32 UTC, adason commented on datasetinsights/commands/download.py
> +@click.command(context_settings=const.CONTEXT_SETTINGS,)
Why extra comma here?

2020-08-21 19:32 UTC, adason commented on datasetinsights/commands/download.py
> +    Unity Simulation
I think it will be better to provide full example instead of just source URI. For example, we should have something like

```
Download from Unity Simulation:

You can specify project_it, run_execution_id, access_token in source-uri

datasetinsights download --source-uri=usim://<access_token>@<project_id>/<run_execution_id> --output=$HOME/data

Alternatively, you can also override access_token such as

datasetinsights download --source-uri=usim://<project_id>/<run_execution_id> --output=$HOME/data --access-token=<access_token>



```

2020-08-21 19:32 UTC, adason commented on datasetinsights/commands/download.py
> +    Groceries
We don't want to list all dataset here. Instead we should simply provide 

```
datasetinsights download --source-uri=http://url.to.file.zip --output=$HOME/data
```

2020-08-21 19:32 UTC, adason commented on datasetinsights/commands/download.py
> +
GCS command example?

2020-08-24 12:06 UTC, AdamPalmarUnity commented on datasetinsights/commands/download.py
> +@click.command(context_settings=const.CONTEXT_SETTINGS,)
This is added automatically by pre-commit

2020-08-24 17:31 UTC, BlairLee commented on datasetinsights/commands/download.py
> +
+1

2020-08-24 17:38 UTC, adason approved these changes

2020-08-24 20:10 UTC, merged